# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsSsm < Formula
  desc "AWS SSM Utility"
  homepage "https://github.com/yasithab/aws-ssm"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yasithab/aws-ssm/releases/download/1.0.1/aws-ssm_Darwin_x86_64.tar.gz"
      sha256 "4c0b4e4291c80e58ab352b96a90919e6256bfad53e357dbed5b96ca7a0e31c08"

      def install
        bin.install "aws-ssm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yasithab/aws-ssm/releases/download/1.0.1/aws-ssm_Darwin_arm64.tar.gz"
      sha256 "f9f7e921d24d897dd4e4ec8a5a6b1ba3d8c0c366fb80b74bafc43aef6b876da4"

      def install
        bin.install "aws-ssm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yasithab/aws-ssm/releases/download/1.0.1/aws-ssm_Linux_x86_64.tar.gz"
        sha256 "ccaa4c4f98bb8c0186c620ad5be9332412f544452c76769fde5f05deb00d6096"

        def install
          bin.install "aws-ssm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yasithab/aws-ssm/releases/download/1.0.1/aws-ssm_Linux_arm64.tar.gz"
        sha256 "edbb3a61f1630e50d4cdde12594dc3097e7cf1dc5ba87bb75a3803409033db14"

        def install
          bin.install "aws-ssm"
        end
      end
    end
  end

  test do
    system "#{bin}/aws-ssm --version"
  end
end
